### ISSUE TITLE
dashboard selects wrong cluster "cluster-name" on refresh

### ISSUE THREAD

**Issue by maaft** [cloudnative-pg/grafana-dashboards#20]
The issue is, that in regex "cluster" is used instead of "exported_cluster".

This leads to:
1. no automatic cluster selection when namespace is selected
2. if entered manually, on next data refresh the cluster-name is lost again

Required dashboard change (regex: change "exported" to "exported_cluster")

```json
{
        "current": {},
        "datasource": {
          "type": "prometheus",
          "uid": "${DS_PROMETHEUS}"
        },
        "definition": "cnpg_collector_up{namespace=~\"$namespace\"}",
        "description": "CNPG Cluster",
        "hide": 0,
        "includeAll": false,
        "label": "Cluster",
        "multi": false,
        "name": "cluster",
        "options": [],
        "query": {
          "query": "cnpg_collector_up{namespace=~\"$namespace\"}",
          "refId": "PrometheusVariableQueryEditor-VariableQuery"
        },
        "refresh": 2,
        "regex": "/\\bexported_cluster\\b=\"(?<text>[^\"]+)/g",
        "skipUrlSync": false,
        "sort": 1,
        "type": "query"
      },
      ```

**Comment by itay-grudev** [comment]
Isn't this fixed in the latest release?

**Comment by mschroeder-fzj** [comment]
While the issue persists a workaround exists, in the values for deploying the PostgreSQL Cluster add:
```yaml
cluster:
  monitoring:
    enabled: true
    podMonitor:
      enabled: true
      metricRelabelings:
        - sourceLabels: [exported_cluster]
          targetLabel: cluster
          action: replace
        - regex: exported_cluster
          action: labeldrop
    prometheusRule:
      enabled: true
```

With the relabeling it worked for me.

Additionally for the Operator I set `fullnameOverride: cloudnative-pg-operator` because some panels have a hardcoded lookup for that.
